import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

st.set_page_config(
    page_title="Port of Oakland Seaport Emissions",
    layout="centered"
)

# --- CSS Injection ---
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Lora:ital,wght@0,400;0,500;1,400&display=swap');

html, body, [class*="css"]  {
    font-family: 'Lora', serif;
    color: #333333;
    background-color: #f9f9f9;
}

h1, h2, h3, h4, h5, h6 {
    font-family: 'DM Sans', sans-serif !important;
    color: #111111;
    font-weight: 500;
}

p, li, .stMarkdown {
    font-family: 'Lora', serif;
    font-size: 1.1rem;
    line-height: 1.6;
    color: #4a4a4a;
}

/* Adjust top padding to look more like an article */
.block-container {
    padding-top: 2rem;
    max-width: 800px;
}

.stMetric label {
    font-family: 'DM Sans', sans-serif !important;
    font-size: 0.9rem;
    color: #666;
}
.stMetric div[data-testid="stMetricValue"] {
    font-family: 'DM Sans', sans-serif !important;
    font-size: 1.8rem;
    color: #111;
}
</style>
""", unsafe_allow_html=True)

# --- Data Loading ---
def load_all_data():
    df = pd.read_csv("data/oakland_emissions_master.csv")
    try:
        df_act = pd.read_csv("data/activity_metrics.csv")
        df_ogv = pd.read_csv("data/ogv_modes.csv")
        df_truck = pd.read_csv("data/truck_modes.csv")
    except FileNotFoundError:
        df_act, df_ogv, df_truck = None, None, None
    return df, df_act, df_ogv, df_truck

df, df_act, df_ogv, df_truck = load_all_data()

# Convert all emissions from US short tons to metric tonnes (MT)
pollutants = ["DPM", "NOx", "SOx", "PM10", "PM2_5", "ROG", "CO", "CO2e"]
for col in pollutants:
    if col in df.columns:
        df[col] = df[col] * 0.907185
    if df_ogv is not None and col in df_ogv.columns:
        df_ogv[col] = df_ogv[col] * 0.907185
    if df_truck is not None and col in df_truck.columns:
        df_truck[col] = df_truck[col] * 0.907185

# --- Page Header ---
st.title("Port of Oakland Seaport Emissions")

st.markdown("""
How much pollution is generated by the Port of Oakland? Which sources are responsible for the most emissions, and how has the Port's air quality profile changed over the last two decades?

This dashboard explores these questions using historical Seaport Air Emissions Inventories to visualize trends in diesel particulate matter, greenhouse gases, and other critical pollutants from 2005 to 2020.

*Note: Cargo volume is measured in **TEU** (Twenty-foot Equivalent Unit), a standard measure for container capacity.*
""")

# --- Filters ---
st.markdown("### Select a Pollutant")
metric_labels = {
    "DPM": "Diesel Particulate Matter (DPM)",
    "ROG": "Reactive Organic Gases (ROG)"
}

col_filter1, col_filter2 = st.columns([1, 1])
with col_filter1:
    pollutant = st.selectbox(
        "Metric",
        options=["DPM", "NOx", "SOx", "PM10", "PM2_5", "ROG", "CO", "CO2e"],
        format_func=lambda x: metric_labels.get(x, x),
        index=0,
        label_visibility="collapsed"
    )

with col_filter2:
    method = st.selectbox(
        "Methodology",
        options=["Historical", "Best Estimate"],
        index=0,
        label_visibility="collapsed"
    )

filtered_df = df[df["Method"] == method].copy()

# --- Common Plotly Layout Tweaks ---
def apply_clean_layout(fig):
    fig.update_layout(
        font=dict(family="DM Sans"),
        plot_bgcolor="rgba(0,0,0,0)",
        paper_bgcolor="rgba(0,0,0,0)",
        margin=dict(l=0, r=0, t=40, b=0),
        xaxis=dict(showgrid=False, zeroline=False),
        yaxis=dict(showgrid=True, gridcolor="#e5e5e5", zeroline=False)
    )
    return fig

# --- KPI Section ---
st.markdown("---")

if method == "Historical":
    latest_year = filtered_df["Year"].max()
    base_year_df = filtered_df[filtered_df["Year"] == 2005]
    latest_year_df = filtered_df[filtered_df["Year"] == latest_year]
    
    base_val = base_year_df[pollutant].sum()
    latest_val = latest_year_df[pollutant].sum()
    
    # Handle edge cases where base_val is 0 to avoid division by zero
    pct_change = ((latest_val - base_val) / base_val * 100) if base_val > 0 else 0

    col1, col2, col3 = st.columns(3)
    col1.metric("2005 Baseline Total", f"{base_val:,.1f} MT")
    col2.metric(f"{latest_year} Total", f"{latest_val:,.1f} MT", delta=f"{pct_change:.1f}%", delta_color="inverse")
    
    if df_act is not None:
        common_years = set(filtered_df["Year"]).intersection(set(df_act["Year"]))
        if common_years:
            latest_common_year = max(common_years)
            latest_teu = df_act[df_act["Year"] == latest_common_year]["TEU"].values[0]
            latest_emissions_val = filtered_df[filtered_df["Year"] == latest_common_year][pollutant].sum()
            intensity = latest_emissions_val / latest_teu
            
            intensity_delta = None
            if 2005 in common_years:
                base_teu = df_act[df_act["Year"] == 2005]["TEU"].values[0]
                base_emiss = filtered_df[filtered_df["Year"] == 2005][pollutant].sum()
                if base_teu > 0 and base_emiss > 0:
                    base_intensity = base_emiss / base_teu
                    intensity_pct_change = ((intensity - base_intensity) / base_intensity) * 100
                    intensity_delta = f"{intensity_pct_change:.1f}%"
            
            if intensity < 0.01:
                # 1 Metric Tonne = 1000 kg
                col3.metric(f"Intensity ({latest_common_year})", f"{intensity * 1000:.2f} kg/TEU", delta=intensity_delta, delta_color="inverse")
            else:
                col3.metric(f"Intensity ({latest_common_year})", f"{intensity:.4f} MT/TEU", delta=intensity_delta, delta_color="inverse")
        else:
            col3.metric("Emissions Intensity", "N/A")
    else:
        col3.metric("Emissions Intensity", "N/A")


# --- Tabs ---
tab1, tab2 = st.tabs(["Emissions Inventory", "Energy & Resilience"])

with tab1:
    # --- Overall Emissions Section ---
    st.markdown("---")
    st.markdown("## Overall Emissions by Source")
    st.markdown(f"""
    Where does the **{pollutant}** generated at the Port come from? This chart shows total annual emissions broken down by major source categories: Ocean-Going Vessels, Harbor Craft, Cargo Handling Equipment, Drayage Trucks, and Locomotives.

    Tracking these totals against the 2005 baseline helps the Port evaluate the success of the Maritime Air Quality Improvement Plan (MAQIP).
    """)

    fig_main = px.bar(
        filtered_df,
        x="Year",
        y=pollutant,
        color="Category",
        barmode="stack",
        color_discrete_sequence=px.colors.qualitative.Set2
    )
    fig_main.update_layout(xaxis=dict(type='category'), hovermode="x unified")
    fig_main = apply_clean_layout(fig_main)
    st.plotly_chart(fig_main, use_container_width=True)

    # --- Port Activity Trends ---
    if df_act is not None:
        st.markdown("---")
        st.markdown("## Port Activity Trends")
        st.markdown("""
        To understand emissions scaling, we have to look at overall Port activity. If throughput increases, we expect emissions to increase unless operational efficiencies or cleaner technologies are introduced.
    
        This chart tracks the volume of cargo processed (TEUs) against the number of truck trips generated.
        """)
    
        fig_act = px.line(
            df_act, 
            x="Year", 
            y=["TEU", "TruckTrips"], 
            color_discrete_sequence=["#0f172a", "#3b82f6"] # Deep slate and bright blue for contrast
        )
        fig_act.update_traces(line=dict(width=3))
        fig_act.update_layout(hovermode="x unified")
        fig_act = apply_clean_layout(fig_act)
        st.plotly_chart(fig_act, use_container_width=True)

    # --- Ocean-Going Vessels (OGV) ---
    st.markdown("---")
    st.markdown(f"## Ocean-Going Vessel **{pollutant}** by Mode")
    st.markdown(f"""
    Ocean-Going Vessels (OGVs) are traditionally the largest single source of emissions at the Port. However, their emissions profile isn't just generated while docked.
    
    The geographic domain for tracking OGV **{pollutant}** begins the moment a ship passes under the Golden Gate Bridge. This chart breaks down emissions by the ship's specific operating mode, illustrating the massive impact of Shore Power (plugging into the electrical grid while at Berth) and vessel speed reduction zones.
    """)
    
    fig_ogv = px.bar(
        df_ogv, 
        x="Year", 
        y=pollutant, 
        color="Mode", 
        barmode="stack", 
        color_discrete_sequence=px.colors.qualitative.Set2
    )
    fig_ogv = apply_clean_layout(fig_ogv)
    st.plotly_chart(fig_ogv, use_container_width=True)

    # --- Drayage Trucks ---
    st.markdown("---")
    st.markdown(f"## Drayage Truck **{pollutant}** by Mode")
    st.markdown(f"""
    Drayage trucks move containers in and out of the terminal gates. Tracking their operating modes—whether they are idling in queue at the gate or actively driving on surface roads—helps identify operational bottlenecks.
    
    *Note: A sharp increase in estimated emissions or activity may be the result of updated data collection methodologies (e.g., switching to automated eModal gate counts) rather than a physical spike in traffic.*
    """)
    
    fig_truck = px.bar(
        df_truck, 
        x="Year", 
        y=pollutant, 
        color="Mode", 
        barmode="stack", 
        color_discrete_sequence=px.colors.qualitative.Set2
    )
    fig_truck = apply_clean_layout(fig_truck)
    st.plotly_chart(fig_truck, use_container_width=True)

with tab2:
    if df_act is not None:
        # --- Shore Power Plug-in Rates ---
        st.markdown("---")
        st.markdown("## Shore Power Plug-in Rates")
        st.markdown("""
        "Shore Power" or "Cold Ironing" allows Ocean-Going Vessels to plug into the electrical grid while at berth, allowing them to shut off their auxiliary diesel engines. This has been a massive driver of emissions reductions.
    
        This chart tracks the percentage of total vessel calls that successfully connected to Shore Power.
        """)
    
        if "ShorePowerPluginRate" in df_act.columns:
            # Calculate the absolute number of plugged-in vessels
            df_act["PluggedInVessels"] = df_act["VesselCalls"] * (df_act["ShorePowerPluginRate"] / 100)
            
            fig_shore = make_subplots(specs=[[{"secondary_y": True}]])
            
            fig_shore.add_trace(
                go.Bar(
                    x=df_act["Year"], 
                    y=df_act["VesselCalls"], 
                    name="Total Vessel Calls",
                    marker_color="#cbd5e1"
                ),
                secondary_y=False,
            )
            
            fig_shore.add_trace(
                go.Scatter(
                    x=df_act["Year"], 
                    y=df_act["PluggedInVessels"], 
                    name="Plugged-In Vessels",
                    mode='lines+markers',
                    line=dict(color="#10b981", width=3)
                ),
                secondary_y=True,
            )
            
            fig_shore.update_layout(
                hovermode="x unified",
                barmode='group'
            )
            fig_shore.update_yaxes(title_text="Total Vessel Calls", secondary_y=False)
            fig_shore.update_yaxes(title_text="Plugged-In Vessels", secondary_y=True)
            
            fig_shore = apply_clean_layout(fig_shore)
            st.plotly_chart(fig_shore, use_container_width=True)

        # --- Renewable Energy Procurement ---
        st.markdown("---")
        st.markdown("## Renewable Energy Procurement")
        st.markdown("""
        The Port of Oakland operates as a publicly owned electric utility. This chart tracks the percentage of the Port's electricity procurement that comes from renewable and zero-carbon sources (such as geothermal, solar, and hydroelectric power).
        """)
        
        if "RenewableEnergyPercent" in df_act.columns:
            fig_renew = px.area(
                df_act, 
                x="Year", 
                y="RenewableEnergyPercent", 
                color_discrete_sequence=["#0ea5e9"]
            )
            fig_renew.update_traces(fillcolor='rgba(14, 165, 233, 0.3)', line=dict(width=3))
            fig_renew.update_layout(
                hovermode="x unified",
                yaxis=dict(title="Renewable Energy (%)", range=[0, 100])
            )
            fig_renew = apply_clean_layout(fig_renew)
            st.plotly_chart(fig_renew, use_container_width=True)

# Footer
st.markdown("---")
st.caption("Data source: Official Port of Oakland Seaport Air Emissions Inventories. Dashboard designed for clarity and narrative analysis.")
